### ISSUE TITLE
Add Twitter -- solved

### ISSUE THREAD

**Issue by mitar** [peer/mind-landing#2]
We have it: https://twitter.com/PeerMind

**Comment by shun-lin** [comment]
added

**Comment by mitar** [comment]
Hm, Twitter should point to Twitter.

Also, when you are making change to git, please [reference the issue](https://help.github.com/articles/autolinked-references-and-urls/) you are working on from the commit. So that it is easier to understand what commit is doing what, and also GitHub will link the commit and issue together, so it is easier to understand the changes.

This also means that it is important to split changes into multiple commits, so that each commit is a rounded change, and not mixed (too much) with other changes.

**Comment by shun-lin** [comment]
updated, sorry for being MIA for a while for midterm 1's for my classes.
